[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "skoda-public-api"
version = "1.1.0"
authors = [
  { name = "Mobility Lab, VŠB-TUO" },
  { name = "TomVSB", email = "tomas.mrovec@vsb.cz" },
  { name="net0045", email="stepan.netolicky@vsb.cz" },
  { name="mag0051", email="david.magyarics@vsb.cz" },
]
maintainers = [
  { name="mag0051", email="david.magyarics@vsb.cz" },
  { name = "TomVSB", email = "tomas.mrovec@vsb.cz" },
]
description = "Asynchronous Python library for the Škoda public API"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Framework :: AsyncIO",
]
dependencies = [
    "aiohttp>=3.9.0",
    "pydantic>=2.5.0",
]

[project.urls]
"Homepage" = "https://github.com/mobility-lab-vsb/skoda-public-api"
"Bug Tracker" = "https://github.com/mobility-lab-vsb/skoda-public-api/issues"

[project.scripts]
skodactl = "skoda_public_api.cli:cli"

[tool.pytest.ini_options]
pythonpath = ["src/skoda_public_api"]

[project.optional-dependencies]
test = [
    "pytest>=9.0.0",
    "pytest-asyncio>=0.23.0",
    "aresponses>=3.0.0",
]
cli = [
    "asyncclick ~=8.1",
    "coloredlogs ~=15.0",
    "pygments ~=2.18",
    "pyyaml ~=6.0",
]
