from enum import Enum

class TemperatureUnit(str, Enum):
    CELSIUS = "CELSIUS"
    FAHRENHEIT = "FAHRENHEIT"
    UNKNOWN = "UNKNOWN"

class OnOffState(str, Enum):
    ON = "ON"
    OFF = "OFF"
    UNKNOWN = "UNKNOWN"
    UNSUPPORTED = "UNSUPPORTED"

class LockState(str, Enum):
    LOCKED = "LOCKED"
    UNLOCKED = "UNLOCKED"
    UNKNOWN = "UNKNOWN"

class OpenCloseState(str, Enum):
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    UNKNOWN = "UNKNOWN"
    UNSUPPORTED = "UNSUPPORTED"

class YesNoState(str, Enum):
    YES = "YES"
    NO = "NO"
    UNKNOWN = "UNKNOWN"

class DoorsState(str, Enum):
    YES = "YES"
    NO = "NO"
    TRUNK_OPENED = "TRUNK_OPENED"
    OPENED = "OPENED"
    UNKNOWN = "UNKNOWN"

class AuxiliaryHeatingState(str, Enum):
    HEATING = "HEATING"
    VENTILATION = "VENTILATION"
    OFF = "OFF"
    HEATING_AUXILIARY = "HEATING_AUXILIARY"
    UNKNOWN = "UNKNOWN"
    UNSUPPORTED = "UNSUPPORTED"

class AuxiliaryHeatingStartMode(str, Enum):
    HEATING = "HEATING"
    VENTILATION = "VENTILATION"
   
class VentilationState(str, Enum):
    VENTILATION = "VENTILATION"
    PREHEATING = "PREHEATING"
    OFF = "OFF"
    UNKNOWN = "UNKNOWN"
    UNSUPPORTED = "UNSUPPORTED"

class HeaterSourceState(str, Enum):
    AUTOMATIC = "AUTOMATIC"
    ELECTRIC = "ELECTRIC"

class ChargeType(str, Enum):
    AC = "AC"
    DC = "DC"
    OFF = "OFF"

class ChargingState(str, Enum):
    CONNECT_CABLE = "CONNECT_CABLE"
    CHARGING = "CHARGING"
    CONSERVING = "CONSERVING"
    READY_FOR_CHARGING = "READY_FOR_CHARGING"
    DISCHARGING = "DISCHARGING"
    CHARGING_INTERRUPTED = "CHARGING_INTERRUPTED"

class ChargeMode(str, Enum):
    MANUAL = "MANUAL"
    TIMER = "TIMER"
    TIMER_CHARGING_WITH_CLIMATISATION = "TIMER_CHARGING_WITH_CLIMATISATION"
    PREFERRED_CHARGING_TIMES = "PREFERRED_CHARGING_TIMES"
    ONLY_OWN_CURRENT = "ONLY_OWN_CURRENT"
    IMMEDIATE_DISCHARGING = "IMMEDIATE_DISCHARGING"
    HOME_STORAGE_CHARGING = "HOME_STORAGE_CHARGING"

class ChargeCareModeState(str, Enum):
    ACTIVATED = "ACTIVATED"
    DEACTIVATED = "DEACTIVATED"

class AutoUnlockPlugState(str, Enum):
    PERMANENT = "PERMANENT"
    OFF = "OFF"

class MaxChargeCurrentAcState(str, Enum):
    REDUCED = "REDUCED"
    MAXIMUM = "MAXIMUM"

class MovementState(str, Enum):
    IN_MOTION = "IN_MOTION"
    PARKED = "PARKED"

class VehicleErrorState(str, Enum):
    VEHICLE_STATUS_UNSUPPORTED = "VEHICLE_STATUS_UNSUPPORTED"
    VEHICLE_STATUS_DISABLED = "VEHICLE_STATUS_DISABLED"
    VEHICLE_STATUS_UNAVAILABLE = "VEHICLE_STATUS_UNAVAILABLE"
    DRIVING_RANGE_UNSUPPORTED = "DRIVING_RANGE_UNSUPPORTED"
    DRIVING_RANGE_DISABLED = "DRIVING_RANGE_DISABLED"
    DRIVING_RANGE_UNAVAILABLE = "DRIVING_RANGE_UNAVAILABLE"
    ODOMETER_UNSUPPORTED = "ODOMETER_UNSUPPORTED"
    ODOMETER_DISABLED = "ODOMETER_DISABLED"
    ODOMETER_UNAVAILABLE = "ODOMETER_UNAVAILABLE"
    PARKING_POSITION_UNSUPPORTED = "PARKING_POSITION_UNSUPPORTED"
    PARKING_POSITION_DISABLED = "PARKING_POSITION_DISABLED"
    PARKING_POSITION_UNAVAILABLE = "PARKING_POSITION_UNAVAILABLE"
    AIR_CONDITIONING_UNSUPPORTED = "AIR_CONDITIONING_UNSUPPORTED"
    AIR_CONDITIONING_DISABLED = "AIR_CONDITIONING_DISABLED"
    AIR_CONDITIONING_UNAVAILABLE = "AIR_CONDITIONING_UNAVAILABLE"
    AUXILIARY_HEATING_UNSUPPORTED = "AUXILIARY_HEATING_UNSUPPORTED"
    AUXILIARY_HEATING_DISABLED = "AUXILIARY_HEATING_DISABLED"
    AUXILIARY_HEATING_UNAVAILABLE = "AUXILIARY_HEATING_UNAVAILABLE"
    ACTIVE_VENTILATION_UNSUPPORTED = "ACTIVE_VENTILATION_UNSUPPORTED"
    ACTIVE_VENTILATION_DISABLED = "ACTIVE_VENTILATION_DISABLED"
    ACTIVE_VENTILATION_UNAVAILABLE = "ACTIVE_VENTILATION_UNAVAILABLE"
    CHARGING_UNSUPPORTED = "CHARGING_UNSUPPORTED"
    CHARGING_DISABLED = "CHARGING_DISABLED"
    CHARGING_UNAVAILABLE = "CHARGING_UNAVAILABLE"
