name: Publish to Production PyPI

# Trigger on standard release
on:
  release:
    types: [released]

jobs:
  build-and-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest

    environment: pypi
    
    # OIDC
    permissions:
      id-token: write  
      contents: read   

    steps:
      - name: Repository checkout
        uses: actions/checkout@v4

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Dependencies installation
        run: python -m pip install --upgrade pip build

      - name: Dependencies build
        run: python -m build

      - name: PyPI publish
        uses: pypa/gh-action-pypi-publish@release/v1